### PR TITLE
Use pure functions.

### PR DESCRIPTION
**Pull request by gajus**
Views cannot have state. Using pure functions makes it easier to read the examples.

### CODE REVIEW

**Comment by zpao** [comment]
I don't want to switch all of the code blocks over (I like the explicitness of using `createClass` for documentation) but wouldn't mind some notes in the readme that makes it clear that anything you can use in React you can use here, including functional components.

**Comment by zpao** [comment]
It's 2 years later (yikes) and functional components are totally normal now so I'm game for this if you wanted to revisit.

**Comment by vnglst** [comment]
Hi there @zpao, I just switched to `express-react-views` from `.ejs` and I really like it! So much more flexible and familiar (for me at least) than the other solutions available like Pug/Jade. 

Can I help with this? Seems like a good first issue for me. If @gajus is ok with that I'll update his PR to fix the merge conflicts and make sure the coding style is in line with the docs on the reactjs.org website.

**Comment by zpao** [comment]
I had done this a while back and forgot to push :(. Readme has functional components now.

**Pull request closed without merging**
