### PR TITLE
Update to Babel v7

### LINKED ISSUE #126: Update to Babel 7
Please update code and package.json to use `@babel/register, @babel/preset-env and @babel/preset-react` as new babel core isn't compatible to old packages (babel-preset-env, babel-preset-react and babel-register)

### PR DESCRIPTION
**Pull request by arthurfranca**
close #126

### CODE REVIEW

**Comment by arthurfranca** [comment]
@zpao @franklinjavier done. i guess now it's all good :+1:

**Comment by onatm** [comment]
@zpao babel 7.0 has been officially released. Could you re-review this PR?

**Comment by onatm** [comment]
Is there any ETA of the new release?

**Comment by szarouski** [comment]
Until this gets published workaround is to install from github:
```json
"express-react-views": "https://github.com/reactjs/express-react-views.git#f9ac87f5fee8c8ed10d545f001ea24c949d0bdaf",
```
Note that f9ac87f5f... is the latest commit at the moment. You might want to use some other commit id.

**Comment by zpao** [comment]
v0.11 is now published.

**Pull request merged**
