### PR TITLE
Update to Babel 6

### PR DESCRIPTION
**Pull request by lijunle**
- Update to babel 6 with React preset.
- Update README document.
- Exposing bug https://github.com/npm/npm/issues/10541

### CODE REVIEW

**Comment by lijunle** [comment]
Hi, @zpao 

Could you please look into this?

**Comment by christinJiang** [comment]
I am newer, how to run this project? Could you please write down the start command?

**Comment by sent1nel** [comment]
+1 I'd like this merged as well, I just did this work on my own branch and was about to open a pull request.

**Comment by zpao** [comment]
Sorry for the delay - it's been a busy couple months and I haven't had a chance to give this project much attention.

I'll give this a little bit more thought in the next couple weeks. At a quick glance, it seems like a great start but I may want to do something differently around the presets.

**Comment by zpao** [comment]
I ended up doing this myself with a bit more to it but I really appreciate the effort! v0.10 (just published) now uses Babel 6.

**Comment by lijunle** [comment]
Great thanks for handling this. :)
2016年2月9日 09:40，"Paul O’Shannessy" <notifications@github.com>写道：

**Pull request closed without merging**
