### PR TITLE
Added client mounting

### PR DESCRIPTION
**Pull request by Zemelia**
Hi @zpao, we added client mounting ability to express-react-views. Can you look to this and maybe there will be a chance to merge our code with your?
There would be great to hear some recommendations or comments about this.
Thanks.

### CODE REVIEW

**Comment by landau** [comment]
You should probably remove commits that are unrelated to this module. You have changes in `package.json`, the `changelog` and more that will never merge.

**Comment by idSnig** [comment]
@landau , we are understand that this code not for merge at the moment (it's only for testing and our github experience), we need some response about main idea of rendering system.

btw, thanks for responce.

**Comment by landau** [comment]
Ah. Cool. I'd point the maintainers to **exactly** what you want them to look at in this PR. I'd also explain how it works. This is a decent sized diff and it's probably safe to bet that this module is pretty low on FB's totem pole in terms of maintenance and features. Good luck! :)

**Comment by zpao** [comment]
Yea @landau is pretty spot on. I'd love to see some comments in the PR about why you made some decisions and any architectural differences. A couple super quick things I noticed (outside of architecture):

- Why are you blindly caching the result? That really should be an option and probably off by default (also, see next point). How do other Express view engines handle this?
- Why are you no longer clearing the module cache? That was a big deal for the edit & refresh workflow.

**Comment by zpao** [comment]
No update so closing out.

**Pull request closed without merging**
